"type:docs":
  - "**/*.md"
  - "**/*.txt"

"type:design":
  - "**/*.css"
  - "**/*.html"
  - "Images/**/*"
  - "otherStylesheet/**/*"

"type:devops":
  - ".github/**/*"
  - ".gitignore"

"type:testing":
  - "**/*.test.*"
  - "**/*.spec.*"
  - "tests/**/*"
